from com.android.monkeyrunner import MonkeyRunner, MonkeyDevice
device = MonkeyRunner.waitForConnection()
device.startActivity(component='com.android.calculator2/.Calculator')
device.press('KEYCODE_1', MonkeyDevice.DOWN_AND_UP)
device.press('KEYCODE_PLUS', MonkeyDevice.DOWN_AND_UP)
device.press('KEYCODE_2', MonkeyDevice.DOWN_AND_UP)
device.press('KEYCODE_PLUS', MonkeyDevice.DOWN_AND_UP)
device.press('KEYCODE_3', MonkeyDevice.DOWN_AND_UP)
device.press('KEYCODE_PLUS', MonkeyDevice.DOWN_AND_UP)
device.press('KEYCODE_4', MonkeyDevice.DOWN_AND_UP)
device.press('KEYCODE_PLUS', MonkeyDevice.DOWN_AND_UP)
device.press('KEYCODE_5', MonkeyDevice.DOWN_AND_UP)
device.press('KEYCODE_ENTER', MonkeyDevice.DOWN_AND_UP)
MonkeyRunner.sleep(2)
result=device.takeSnapshot()
result.writeToFile('shot1.png','png')